name: LinkedIn Data Pipeline

permissions:
  contents: write

on:
  schedule:
    - cron: '*/20 * * * *'     # every 5 minutes
  workflow_dispatch:

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data pipeline
        env:
          SCRAPINGDOG_API_KEY: ${{ secrets.SCRAPINGDOG_API_KEY }}
          SUPABASE_URL:        ${{ secrets.SUPABASE_URL }}      # e.g. https://xxxx.supabase.co
          SUPABASE_KEY:        ${{ secrets.SUPABASE_KEY }}      # anon key ok for public-read bucket; service key if private
          COMPANY_LINKID:      extrastaff-recruitment
          COMPANY_URL:         https://www.linkedin.com/company/extrastaff-recruitment
          BUCKET_NAME:         Marketing Database                # <-- your bucket with space; code URL-encodes it
        run: python main.py

      # Optional: keep CSVs versioned in repo
      - name: Commit updated CSVs
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add linkedin_followers.csv lnkdn.csv || true
          git commit -m "Update CSVs [skip ci]" || echo "No changes"
          git push || true
